name: Lint

on: push
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-json:
    runs-on: ubuntu-latest
    name: With JQ
    steps:
    - name: ğŸ“¥ Checkout the repository
      uses: actions/checkout@v4.1.1

    - name: ğŸƒ Run validation
      run: jq -r -e -c . tests/fixtures/*.json
